### ISSUE TITLE
Add `part` attributes to inner elements to allow custom styling via ::part selector

### ISSUE THREAD

**Issue by sovietspaceship** [vscode-elements/elements#204]
See https://developer.mozilla.org/en-US/docs/Web/CSS/::part.

My use case is being able to apply custom styling from outside a component.

This would enable stuff like:

```css
vscode-textarea::part(textarea) {
  border-color: blue !important;
}
```

The implementation would look something like:

```ts
render(): TemplateResult {
    return html`
      ...
      <textarea
        autocomplete=${ifDefined(this.autocomplete)}
        part="textarea"
```

The reason ::part is required is that these examples won't work:

```css
textarea {
  border-color: blue !important;
}

vscode-textarea textarea {
  border-color: blue !important;
}
```

including a potential solution to allow passing custom classes

```ts
class=${classMap({
    monospace: this.monospace,
    ...this.classes
```

due to `textarea` living within the `vscode-textarea` shadow DOM.

I'd create a PR myself, but as this requires updating several components as well as the documentation I'd like to know your opinion on this before committing to it.
